version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch1
    environment:
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch2
    environment:
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  search-ui:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch1:9200
    depends_on:
      - elasticsearch1
      - elasticsearch2

volumes:
  esdata1:
  esdata2:
